version: "3.8"

services:

  #################
  # BACKEND (PHP)
  #################
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: tpk_backend
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      # - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tpk_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  #################
  # FRONTEND (React)
  #################
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    container_name: tpk_frontend
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  #################
  # MYSQL
  #################
  db:
    image: mysql:8.0
    container_name: tpk_db
    restart: always
    environment:
      MYSQL_DATABASE: tpk_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  #################
  # NGINX
  #################
  nginx:
    image: nginx:alpine
    container_name: tpk_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # El backend está montado en /var/www por si tu Nginx
      # también necesitara servir archivos estáticos de Laravel
      - ./backend:/var/www
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
